model_list:

  # - model_name: coder
  #   litellm_params:
  #     model: openai/coder
  #     api_base: http://vllm-coder:8000/v1
  #     api_key: dummy

  - model_name: research
    litellm_params:
      model: openai/research
      api_base: http://vllm-research:8000/v1
      api_key: dummy